apiVersion: v1
kind: Service
metadata:
  name: devops-pipeline-demo
  labels:
    app: devops-pipeline-demo
spec:
  type: ClusterIP

  selector:
    app: devops-pipeline-demo

  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
